(() => {
  const SOMNIA = { chainId: '0xc488', chainName: 'Somnia Shannon Testnet', nativeCurrency: { name: 'STT', symbol: 'STT', decimals: 18 }, rpcUrls: ['https://dream-rpc.somnia.network'], blockExplorerUrls: ['https://shannon-explorer.somnia.network'] };
  const state = { intent: 'buy', asset: 'ETH', amount: '100', currency: 'USD', minutes: '15', wallet: null };
  const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)]; const toast = $('#toast');
  const side = () => `${state.asset} ${state.intent === 'buy' ? 'Up' : 'Down'}`;
  function updatePreview(){ const up=state.intent==='buy'; $('#previewAsset').textContent=state.asset; $('#previewAssetIcon').textContent=state.asset==='ETH'?'Ξ':'₿'; $('#previewAssetIcon').className=`token-icon ${state.asset.toLowerCase()}`; $('#previewWindow').textContent=`${state.minutes} minute window`; $('#previewTitle').textContent=up?'Buying later means a price rise is the risk.':'Selling later means a price fall is the risk.'; $('#previewDescription').textContent=up?`DelayGuard looks for a live ${state.asset} Up Event Contract to protect the wait.`:`DelayGuard looks for a live ${state.asset} Down Event Contract to protect the wait.`; $('#previewSide').textContent=side(); $('#previewExplanation').textContent=up?`${state.asset} rising makes your future purchase more expensive.`:`${state.asset} falling makes your future sale worth less.`; }
  function showToast(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3800)}
  async function ensureSomnia(){ if(!window.ethereum) throw new Error('No browser wallet found. Open DelayGuard in MetaMask or Rabby.'); try{await ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:SOMNIA.chainId}]})}catch(e){if(e.code===4902)await ethereum.request({method:'wallet_addEthereumChain',params:[SOMNIA]});else throw e} }
  async function connect(){ if(!window.ethereum){showToast('No browser wallet found. Open this in MetaMask or Rabby.');return} try{await ensureSomnia(); const [a]=await ethereum.request({method:'eth_requestAccounts'}); state.wallet=a; $('#walletLabel').textContent=`${a.slice(0,6)}…${a.slice(-4)}`; $('#walletButton').classList.add('connected'); showToast('Wallet connected to Somnia Shannon testnet.');}catch(e){showToast(e.message||'Wallet connection was cancelled.')} }
  function createReceipt(){ const id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`; const receipt={id,...state,direction:state.intent==='buy'?'UP':'DOWN',status:'PLAN_READY',createdAt:new Date().toISOString()}; localStorage.setItem('delayguard-plan-v2',JSON.stringify(receipt)); $('#receiptAction').textContent=`${state.intent==='buy'?'Buying':'Selling'} ${state.asset} later`; $('#receiptRisk').textContent=`Protected if ${state.asset} ${state.intent==='buy'?'rises':'falls'}`; $('#receiptAmount').textContent=`Plan: ${state.amount} ${state.currency} · ${state.minutes} minutes`; $('#receiptSide').textContent=side(); $('#receiptStatus').textContent=state.wallet?'Protection plan ready. Wallet is on Somnia Shannon. Run the verified onchain command below to place the Event Contract order.':'Plan ready. Connect a wallet on Somnia Shannon before placing the real testnet protection.'; $('#receiptCard').classList.remove('receipt-updated'); requestAnimationFrame(()=>$('#receiptCard').classList.add('receipt-updated')); location.hash='receipt'; showToast('Protection plan saved.'); }
  $$('.choice').forEach(b=>b.addEventListener('click',()=>{state.intent=b.dataset.intent;$$('.choice').forEach(x=>x.classList.toggle('selected',x===b));updatePreview()})); $$('.time-choice').forEach(b=>b.addEventListener('click',()=>{state.minutes=b.dataset.time;$$('.time-choice').forEach(x=>x.classList.toggle('selected',x===b));updatePreview()})); $('#asset').addEventListener('change',e=>{state.asset=e.target.value;updatePreview()}); $('#amount').addEventListener('input',e=>state.amount=e.target.value.replace(/[^0-9.]/g,'').slice(0,10)||'0'); $('#currency').addEventListener('change',e=>state.currency=e.target.value); $('#protectionForm').addEventListener('submit',e=>{e.preventDefault();if(Number(state.amount)<=0){showToast('Enter an amount bigger than zero.');return}createReceipt()}); $('#walletButton').addEventListener('click',connect);
  if(window.ethereum){ethereum.on?.('accountsChanged',a=>{state.wallet=a[0]||null;if(!state.wallet){$('#walletLabel').textContent='Connect wallet';$('#walletButton').classList.remove('connected')}}); ethereum.on?.('chainChanged',()=>location.reload())}
  updatePreview();
})();
